
server:
  port: 8000
spring:
  data:
  jdbc:
  datasource:
    url: jdbc:mysql://localhost:3306/Hospital?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: r@@T0000
  jpa:
    hibernate:
      ddl-auto: update
  jpa.open-in-view: true